name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildlinux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd  vmd/plugins && make LINUXAMD64
 
  buildosx:
    runs-on: osx-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd  vmd/plugins && make MACOSXX86_64
    
    
